### PR TITLE
stripped art support

### PR DESCRIPTION
**Pull request by janisslsm**
relies on https://github.com/Aliucord/LSPlant/pull/3/

### CODE REVIEW

**Review by rushiiMachine — COMMENTED** [review]
is it possible to submodule xz instead of embedding it directly

**Comment by janisslsm** [comment]
nop, couldn't find a repo that had just xz.

edit: https://github.com/tukaani-project/xz-embedded might be able to use this. seems to be identical to the current embedded one.

**Comment by rushiiMachine** [comment]
workflow should recursively checkout the repo btw

**Comment by janisslsm** [comment]
> workflow should recursively checkout the repo btw

right, will do.

**Comment by janisslsm** [comment]
done.

**Pull request merged**
